// <auto-generated />
using System;
using BattleGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleGame.Api.Migrations
{
    [DbContext(typeof(BattleGameDbContext))]
    [Migration("20261009013740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleGame.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("LevelRequire")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.ToTable("Asset", (string)null);

                    b.HasData(
                        new
                        {
                            AssetId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AssetName = "Hero 1",
                            LevelRequire = 1
                        },
                        new
                        {
                            AssetId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AssetName = "Hero 2",
                            LevelRequire = 3
                        });
                });

            modelBuilder.Entity("BattleGame.Api.Models.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("PlayerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PlayerName")
                        .IsUnique();

                    b.ToTable("Player", (string)null);

                    b.HasData(
                        new
                        {
                            PlayerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Age = "20",
                            Email = "p1@game.com",
                            FullName = "Nguyen Van A",
                            Level = 10,
                            PlayerName = "Player 1"
                        },
                        new
                        {
                            PlayerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Age = "19",
                            Email = "p2@game.com",
                            FullName = "Tran Thi B",
                            Level = 3,
                            PlayerName = "Player 2"
                        },
                        new
                        {
                            PlayerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Age = "23",
                            Email = "p3@game.com",
                            FullName = "Le Van C",
                            Level = 10,
                            PlayerName = "Player 3"
                        });
                });

            modelBuilder.Entity("BattleGame.Api.Models.PlayerAsset", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("PlayerAsset", (string)null);

                    b.HasData(
                        new
                        {
                            PlayerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssetId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            PlayerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssetId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            PlayerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AssetId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("BattleGame.Api.Models.PlayerAsset", b =>
                {
                    b.HasOne("BattleGame.Api.Models.Asset", "Asset")
                        .WithMany("PlayerAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleGame.Api.Models.Player", "Player")
                        .WithMany("PlayerAssets")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BattleGame.Api.Models.Asset", b =>
                {
                    b.Navigation("PlayerAssets");
                });

            modelBuilder.Entity("BattleGame.Api.Models.Player", b =>
                {
                    b.Navigation("PlayerAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
